import {NgModule} from '@angular/core';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {BrowserModule} from '@angular/platform-browser';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

import {
  TuiActiveZoneModule,
  TuiAutoFocusModule,
  TuiElementModule,
  TuiFilterPipeModule,
  TuiLetModule,
  TuiMapperPipeModule,
  TuiMediaModule,
} from '@taiga-ui/cdk';
import {
  TuiButtonModule,
  TuiCalendarModule,
  TuiDataListModule,
  TuiDropdownControllerModule,
  TuiDropdownModule,
  TuiErrorModule,
  TuiExpandModule,
  TuiFormatNumberPipeModule,
  TuiFormatPhonePipeModule,
  TuiGroupModule,
  TuiHintControllerModule,
  TuiHintModule,
  TuiHostedDropdownModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiManualHintModule,
  TuiModeModule,
  TuiPointerHintModule,
  TuiPrimitiveCheckboxModule,
  TuiPrimitiveTextfieldModule,
  TuiRootModule,
  TuiScrollbarModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
  TuiTooltipModule,
} from '@taiga-ui/core';
import {
  TuiAccordionModule,
  TuiActionModule,
  TuiAvatarModule,
  TuiBadgedContentModule,
  TuiBadgeModule,
  TuiBreadcrumbsModule,
  TuiCalendarMonthModule,
  TuiCalendarRangeModule,
  TuiCheckboxBlockModule,
  TuiCheckboxLabeledModule,
  TuiCheckboxModule,
  TuiComboBoxModule,
  TuiDataListWrapperModule,
  TuiDropdownContextModule,
  TuiDropdownSelectionModule,
  TuiFieldErrorModule,
  TuiFilterByInputPipeModule,
  TuiFilterModule,
  TuiHighlightModule,
  TuiInputCopyModule,
  TuiInputCountModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputDateTimeModule,
  TuiInputFileModule,
  TuiInputInlineModule,
  TuiInputModule,
  TuiInputMonthModule,
  TuiInputMonthRangeModule,
  TuiInputNumberModule,
  TuiInputPasswordModule,
  TuiInputPhoneInternationalModule,
  TuiInputPhoneModule,
  TuiInputRangeModule,
  TuiInputSliderModule,
  TuiInputTagModule,
  TuiInputTimeModule,
  TuiIslandModule,
  TuiLazyLoadingModule,
  TuiLineClampModule,
  TuiMarkerIconModule,
  TuiMultiSelectModule,
  TuiPaginationModule,
  TuiPresentModule,
  TuiProgressModule,
  TuiProjectClassModule,
  TuiRadioBlockModule,
  TuiRadioLabeledModule,
  TuiRadioListModule,
  TuiRadioModule,
  TuiSelectModule,
  TuiSliderModule,
  TuiStepperModule,
  TuiTabsModule,
  TuiTagModule,
  TuiTextAreaModule,
  TuiToggleModule,
} from '@taiga-ui/kit';

import {AppComponent} from './app.component';
import {RouterModule} from '@angular/router';

@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    ReactiveFormsModule,
    // Modules for main app.module that should be add once
    TuiRootModule,
    // Modules for your app modules where you use our components
    TuiAccordionModule,
    TuiActionModule,
    TuiActiveZoneModule,
    TuiAvatarModule,
    TuiBadgeModule,
    TuiBadgedContentModule,
    TuiButtonModule,
    TuiCalendarModule,
    TuiCalendarRangeModule,
    TuiCalendarMonthModule,
    TuiCheckboxModule,
    TuiCheckboxBlockModule,
    TuiCheckboxLabeledModule,
    TuiPrimitiveCheckboxModule,
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiDropdownContextModule,
    TuiHostedDropdownModule,
    TuiErrorModule,
    TuiExpandModule,
    TuiFieldErrorModule,
    TuiFilterModule,
    TuiGroupModule,
    TuiMarkerIconModule,
    TuiInputInlineModule,
    TuiInputModule,
    TuiInputDateModule,
    TuiInputCopyModule,
    TuiInputCountModule,
    TuiInputDateTimeModule,
    TuiInputFileModule,
    TuiInputMonthModule,
    TuiInputMonthRangeModule,
    TuiInputNumberModule,
    TuiInputPasswordModule,
    TuiInputPhoneModule,
    TuiInputRangeModule,
    TuiInputDateRangeModule,
    TuiInputSliderModule,
    TuiInputTagModule,
    TuiInputTimeModule,
    TuiInputPhoneInternationalModule,
    TuiPrimitiveTextfieldModule,
    TuiTextAreaModule,
    TuiIslandModule,
    TuiLabelModule,
    TuiLineClampModule,
    TuiLinkModule,
    TuiLoaderModule,
    TuiRadioModule,
    TuiRadioBlockModule,
    TuiRadioLabeledModule,
    TuiRadioListModule,
    TuiComboBoxModule,
    TuiMultiSelectModule,
    TuiSelectModule,
    TuiScrollbarModule,
    TuiInputRangeModule,
    TuiInputSliderModule,
    TuiSliderModule,
    TuiSvgModule,
    TuiTagModule,
    TuiToggleModule,
    TuiTooltipModule,
    TuiBreadcrumbsModule,
    TuiPaginationModule,
    TuiStepperModule,
    TuiTabsModule,
    TuiAutoFocusModule,
    TuiDropdownModule,
    TuiDropdownSelectionModule,
    TuiElementModule,
    TuiHighlightModule,
    TuiHintModule,
    TuiLazyLoadingModule,
    TuiManualHintModule,
    TuiPointerHintModule,
    TuiLetModule,
    TuiMediaModule,
    TuiModeModule,
    TuiPresentModule,
    TuiProgressModule,
    TuiDropdownControllerModule,
    TuiHintControllerModule,
    TuiTextfieldControllerModule,
    TuiFilterPipeModule,
    TuiFormatNumberPipeModule,
    TuiFormatPhonePipeModule,
    TuiMapperPipeModule,
    TuiProjectClassModule,
    TuiFilterByInputPipeModule,
    RouterModule.forRoot([]),
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {
}
